version: "3"

services:

  nginx:
    depends_on:
      - ProfilePageServer
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/sites-available/default
      - ./letsencrypt:/etc/letsencrypt
 
  
  ProfilePageMongoDB:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - MongoDBProfilePage:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=PASSWORD

  ProfilePageServer:
    image: profilepageserver/splodo
    restart: always
    ports:
     - "3000:3000"
    volumes:
      - /images:/server/images
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://NDJISAmxsanjiS4567SDAYD187VGvddFFF:UjewanNUDSAuh237nYDSRWNDuuD72bIoI@ProfilePageMongoDB:27017/splodo?authSource=admin
      CLIENT_URI: https://splodo.com
      SERVERURI: http://splodo.com:3000
      DB_NAME: splododb
      NAME: Samuel
      GOOGLE_CLIENT_ID: GCID
      GOOGLE_CLIENT_SECRET: GCS
    depends_on:
      - ProfilePageMongoDB
    
volumes:
  MongoDBProfilePage: {}
  images: {}
 
