version: "3"

services:

  SplodoMongoDB:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - SplodoMongoDB:/data/db
    environment:
     MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/DB_ROOT_USERNAME
     MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/DB_ROOT_PASSWORD
    secrets:
      - DB_ROOT_USERNAME
      - DB_ROOT_PASSWORD

  SplodoServer:
    image: splodo.server
    restart: always
    ports:
     - "80:80"
     - "443:443"
    volumes:
      - /images:/server/images
    environment:
     PORT: 80
     CLIENT_URI: https://splodo.com
     SERVERURI: https://splodo.com
    secrets:
      - MONGODB_CONNECTION_STRING
      - AUTH_GOOGLE_CLIENT_ID
      - AUTH_GOOGLE_CLIENT_SECRET
    depends_on:
      - SplodoMongoDB

secrets:
  DB_ROOT_USERNAME:
    file: ./values/db_root_username.txt
  DB_ROOT_PASSWORD:
    file: ./values/db_root_password.txt
  MONGODB_CONNECTION_STRING:
    file: ./values/db_root_connection_string.txt
    name: ${MY_SECRET_DATA_ENV_VAR}
  AUTH_GOOGLE_CLIENT_ID:
    file: ./values/google_client_id.txt
  AUTH_GOOGLE_CLIENT_SECRET:
    file: ./values/google_client_secret.txt

volumes:
  SplodoMongoDB: {}
  images: {}

