version: "3"

services:

  nginx:
    depends_on:
      - ProfilePageServer
      - ProfilePageFrontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"
  
  ProfilePageMongoDB:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - MongoDBProfilePage:/data/db

  ProfilePageServer:
    image: profilepageserver/splodo
    restart: always

    ports:
     - "3000:3000"
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://ProfilePageMongoDB:27017/splodo
      CLIENT_URI: http://localhost:3050
      SERVERURI: http://localhost:3000
      DB_NAME: splododb
      NAME: Samuel
      GOOGLE_CLIENT_ID:
      GOOGLE_CLIENT_SECRET:
    depends_on:
      - ProfilePageMongoDB

  ProfilePageFrontend:
    image: profilepagefrontend/splodo
    restart: always
    ports:
     - "8080:8080"
    environment:
      REACT_APP_SOME_ENV_VARIABLE: http://localhost:3000
    depends_on:
      - ProfilePageServer
    
volumes:
  MongoDBProfilePage: {}
