name: splodo-server-ci

on:
  push:
    branches:
      - master
    paths:
      - Splodo.Server/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./Splodo.Server
          file: ./Splodo.Server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/splodo:splodo.server
      -
        name: DO Deployment
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: | 
            cd ${{ secrets.SPLODO_DIRECTORY }}
            docker-compose down
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/splodo:splodo.server -f
             docker-compose up -d
