name: splodo-map-ci

on:
  push:
    branches:
      - master
    paths:
      - Splodo.Map/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./Splodo.Map
          file: ./Splodo.Map/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/splodo:splodo.map
      -
         name: DO Deployment
         uses: appleboy/ssh-action@v0.1.2
         with:
           host: ${{secrets.SSH_HOST}}
           key: ${{secrets.SSH_KEY}}
           username: ${{secrets.SSH_USERNAME}}

           script: | 
             mkdir DEPLOYMENTTESTTTTT
      
